const Koa = require('koa')
const router = require('koa-router')()
const bodyparser = require('koa-bodyparser')
const staticServer = require('koa-static')
const base = require('./routes/base')
const api = require('./routes/api')
const test = require('./routes/test')
const cors = require('koa-cors')
const app = new Koa()
app.use(cors())
app.use(staticServer('./../fe/dist'))
app.use(bodyparser())
app.use(router.routes())

router.use('/base', base.routes(), base.allowedMethods())
router.use('/api', api.routes(), api.allowedMethods())
router.use('/test', test.routes(), test.allowedMethods())

app.listen('3000')
